//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.07 at 12:14:51 PM PST 
//


package com.csra.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllergyIntoleranceCategory-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AllergyIntoleranceCategory-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="food"/>
 *     &lt;enumeration value="medication"/>
 *     &lt;enumeration value="environment"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AllergyIntoleranceCategory-list")
@XmlEnum
public enum AllergyIntoleranceCategoryList {


    /**
     * Any substance consumed to provide nutritional support for the body.
     * 
     */
    @XmlEnumValue("food")
    FOOD("food"),

    /**
     * Substances administered to achieve a physiological effect.
     * 
     */
    @XmlEnumValue("medication")
    MEDICATION("medication"),

    /**
     * Substances that are encountered in the environment.
     * 
     */
    @XmlEnumValue("environment")
    ENVIRONMENT("environment"),

    /**
     * Other substances that are not covered by any other category.
     * 
     */
    @XmlEnumValue("other")
    OTHER("other");
    private final java.lang.String value;

    AllergyIntoleranceCategoryList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static AllergyIntoleranceCategoryList fromValue(java.lang.String v) {
        for (AllergyIntoleranceCategoryList c: AllergyIntoleranceCategoryList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
