//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.10 at 05:13:17 PM PST 
//


package com.csra.fhir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have a value for at least one of the defined elements, an @id referenced from the Narrative, or extensions
 * 
 * <p>Java class for Extension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Extension">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}Element">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="valueBoolean" type="{http://hl7.org/fhir}boolean"/>
 *           &lt;element name="valueInteger" type="{http://hl7.org/fhir}integer"/>
 *           &lt;element name="valueDecimal" type="{http://hl7.org/fhir}decimal"/>
 *           &lt;element name="valueBase64Binary" type="{http://hl7.org/fhir}base64Binary"/>
 *           &lt;element name="valueInstant" type="{http://hl7.org/fhir}instant"/>
 *           &lt;element name="valueString" type="{http://hl7.org/fhir}string"/>
 *           &lt;element name="valueUri" type="{http://hl7.org/fhir}uri"/>
 *           &lt;element name="valueDate" type="{http://hl7.org/fhir}date"/>
 *           &lt;element name="valueDateTime" type="{http://hl7.org/fhir}dateTime"/>
 *           &lt;element name="valueTime" type="{http://hl7.org/fhir}time"/>
 *           &lt;element name="valueCode" type="{http://hl7.org/fhir}code"/>
 *           &lt;element name="valueOid" type="{http://hl7.org/fhir}oid"/>
 *           &lt;element name="valueUuid" type="{http://hl7.org/fhir}uuid"/>
 *           &lt;element name="valueId" type="{http://hl7.org/fhir}id"/>
 *           &lt;element name="valueUnsignedInt" type="{http://hl7.org/fhir}unsignedInt"/>
 *           &lt;element name="valuePositiveInt" type="{http://hl7.org/fhir}positiveInt"/>
 *           &lt;element name="valueMarkdown" type="{http://hl7.org/fhir}markdown"/>
 *           &lt;element name="valueAnnotation" type="{http://hl7.org/fhir}Annotation"/>
 *           &lt;element name="valueAttachment" type="{http://hl7.org/fhir}Attachment"/>
 *           &lt;element name="valueIdentifier" type="{http://hl7.org/fhir}Identifier"/>
 *           &lt;element name="valueCodeableConcept" type="{http://hl7.org/fhir}CodeableConcept"/>
 *           &lt;element name="valueCoding" type="{http://hl7.org/fhir}Coding"/>
 *           &lt;element name="valueQuantity" type="{http://hl7.org/fhir}Quantity"/>
 *           &lt;element name="valueRange" type="{http://hl7.org/fhir}Range"/>
 *           &lt;element name="valuePeriod" type="{http://hl7.org/fhir}Period"/>
 *           &lt;element name="valueRatio" type="{http://hl7.org/fhir}Ratio"/>
 *           &lt;element name="valueReference" type="{http://hl7.org/fhir}Reference"/>
 *           &lt;element name="valueSampledData" type="{http://hl7.org/fhir}SampledData"/>
 *           &lt;element name="valueSignature" type="{http://hl7.org/fhir}Signature"/>
 *           &lt;element name="valueHumanName" type="{http://hl7.org/fhir}HumanName"/>
 *           &lt;element name="valueAddress" type="{http://hl7.org/fhir}Address"/>
 *           &lt;element name="valueContactPoint" type="{http://hl7.org/fhir}ContactPoint"/>
 *           &lt;element name="valueTiming" type="{http://hl7.org/fhir}Timing"/>
 *           &lt;element name="valueMeta" type="{http://hl7.org/fhir}Meta"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="url" use="required" type="{http://hl7.org/fhir}uri-primitive" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Extension", propOrder = {
    "valueBooleanOrValueIntegerOrValueDecimal"
})
public class Extension
    extends Element
{

    @XmlElements({
        @XmlElement(name = "valueBoolean", type = Boolean.class),
        @XmlElement(name = "valueInteger", type = Integer.class),
        @XmlElement(name = "valueDecimal", type = Decimal.class),
        @XmlElement(name = "valueBase64Binary", type = Base64Binary.class),
        @XmlElement(name = "valueInstant", type = Instant.class),
        @XmlElement(name = "valueString", type = com.csra.fhir.String.class),
        @XmlElement(name = "valueUri", type = Uri.class),
        @XmlElement(name = "valueDate", type = Date.class),
        @XmlElement(name = "valueDateTime", type = DateTime.class),
        @XmlElement(name = "valueTime", type = Time.class),
        @XmlElement(name = "valueCode", type = Code.class),
        @XmlElement(name = "valueOid", type = Oid.class),
        @XmlElement(name = "valueUuid", type = Uuid.class),
        @XmlElement(name = "valueId", type = Id.class),
        @XmlElement(name = "valueUnsignedInt", type = UnsignedInt.class),
        @XmlElement(name = "valuePositiveInt", type = PositiveInt.class),
        @XmlElement(name = "valueMarkdown", type = Markdown.class),
        @XmlElement(name = "valueAnnotation", type = Annotation.class),
        @XmlElement(name = "valueAttachment", type = Attachment.class),
        @XmlElement(name = "valueIdentifier", type = Identifier.class),
        @XmlElement(name = "valueCodeableConcept", type = CodeableConcept.class),
        @XmlElement(name = "valueCoding", type = Coding.class),
        @XmlElement(name = "valueQuantity", type = Quantity.class),
        @XmlElement(name = "valueRange", type = Range.class),
        @XmlElement(name = "valuePeriod", type = Period.class),
        @XmlElement(name = "valueRatio", type = Ratio.class),
        @XmlElement(name = "valueReference", type = Reference.class),
        @XmlElement(name = "valueSampledData", type = SampledData.class),
        @XmlElement(name = "valueSignature", type = Signature.class),
        @XmlElement(name = "valueHumanName", type = HumanName.class),
        @XmlElement(name = "valueAddress", type = Address.class),
        @XmlElement(name = "valueContactPoint", type = ContactPoint.class),
        @XmlElement(name = "valueTiming", type = Timing.class),
        @XmlElement(name = "valueMeta", type = Meta.class)
    })
    protected Element valueBooleanOrValueIntegerOrValueDecimal;
    @XmlAttribute(name = "url", required = true)
    protected java.lang.String url;

    /**
     * Gets the value of the valueBooleanOrValueIntegerOrValueDecimal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     {@link Integer }
     *     {@link Decimal }
     *     {@link Base64Binary }
     *     {@link Instant }
     *     {@link com.csra.fhir.String }
     *     {@link Uri }
     *     {@link Date }
     *     {@link DateTime }
     *     {@link Time }
     *     {@link Code }
     *     {@link Oid }
     *     {@link Uuid }
     *     {@link Id }
     *     {@link UnsignedInt }
     *     {@link PositiveInt }
     *     {@link Markdown }
     *     {@link Annotation }
     *     {@link Attachment }
     *     {@link Identifier }
     *     {@link CodeableConcept }
     *     {@link Coding }
     *     {@link Quantity }
     *     {@link Range }
     *     {@link Period }
     *     {@link Ratio }
     *     {@link Reference }
     *     {@link SampledData }
     *     {@link Signature }
     *     {@link HumanName }
     *     {@link Address }
     *     {@link ContactPoint }
     *     {@link Timing }
     *     {@link Meta }
     *     
     */
    public Element getValueBooleanOrValueIntegerOrValueDecimal() {
        return valueBooleanOrValueIntegerOrValueDecimal;
    }

    /**
     * Sets the value of the valueBooleanOrValueIntegerOrValueDecimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     {@link Integer }
     *     {@link Decimal }
     *     {@link Base64Binary }
     *     {@link Instant }
     *     {@link com.csra.fhir.String }
     *     {@link Uri }
     *     {@link Date }
     *     {@link DateTime }
     *     {@link Time }
     *     {@link Code }
     *     {@link Oid }
     *     {@link Uuid }
     *     {@link Id }
     *     {@link UnsignedInt }
     *     {@link PositiveInt }
     *     {@link Markdown }
     *     {@link Annotation }
     *     {@link Attachment }
     *     {@link Identifier }
     *     {@link CodeableConcept }
     *     {@link Coding }
     *     {@link Quantity }
     *     {@link Range }
     *     {@link Period }
     *     {@link Ratio }
     *     {@link Reference }
     *     {@link SampledData }
     *     {@link Signature }
     *     {@link HumanName }
     *     {@link Address }
     *     {@link ContactPoint }
     *     {@link Timing }
     *     {@link Meta }
     *     
     */
    public void setValueBooleanOrValueIntegerOrValueDecimal(Element value) {
        this.valueBooleanOrValueIntegerOrValueDecimal = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setUrl(java.lang.String value) {
        this.url = value;
    }

}
