//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.07 at 12:14:51 PM PST 
//


package com.csra.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HTTPVerb-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HTTPVerb-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GET"/>
 *     &lt;enumeration value="POST"/>
 *     &lt;enumeration value="PUT"/>
 *     &lt;enumeration value="DELETE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HTTPVerb-list")
@XmlEnum
public enum HTTPVerbList {


    /**
     * HTTP GET
     * 
     */
    GET,

    /**
     * HTTP POST
     * 
     */
    POST,

    /**
     * HTTP PUT
     * 
     */
    PUT,

    /**
     * HTTP DELETE
     * 
     */
    DELETE;

    public java.lang.String value() {
        return name();
    }

    public static HTTPVerbList fromValue(java.lang.String v) {
        return valueOf(v);
    }

}
