//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.05 at 04:54:01 PM PST 
//


package com.csra.fhir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceContainer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://hl7.org/fhir}Account"/>
 *         &lt;element ref="{http://hl7.org/fhir}AllergyIntolerance"/>
 *         &lt;element ref="{http://hl7.org/fhir}Appointment"/>
 *         &lt;element ref="{http://hl7.org/fhir}AppointmentResponse"/>
 *         &lt;element ref="{http://hl7.org/fhir}AuditEvent"/>
 *         &lt;element ref="{http://hl7.org/fhir}Basic"/>
 *         &lt;element ref="{http://hl7.org/fhir}Binary"/>
 *         &lt;element ref="{http://hl7.org/fhir}BodySite"/>
 *         &lt;element ref="{http://hl7.org/fhir}Bundle"/>
 *         &lt;element ref="{http://hl7.org/fhir}CarePlan"/>
 *         &lt;element ref="{http://hl7.org/fhir}Claim"/>
 *         &lt;element ref="{http://hl7.org/fhir}ClaimResponse"/>
 *         &lt;element ref="{http://hl7.org/fhir}ClinicalImpression"/>
 *         &lt;element ref="{http://hl7.org/fhir}Communication"/>
 *         &lt;element ref="{http://hl7.org/fhir}CommunicationRequest"/>
 *         &lt;element ref="{http://hl7.org/fhir}Composition"/>
 *         &lt;element ref="{http://hl7.org/fhir}ConceptMap"/>
 *         &lt;element ref="{http://hl7.org/fhir}Condition"/>
 *         &lt;element ref="{http://hl7.org/fhir}Conformance"/>
 *         &lt;element ref="{http://hl7.org/fhir}Contract"/>
 *         &lt;element ref="{http://hl7.org/fhir}Coverage"/>
 *         &lt;element ref="{http://hl7.org/fhir}DataElement"/>
 *         &lt;element ref="{http://hl7.org/fhir}DetectedIssue"/>
 *         &lt;element ref="{http://hl7.org/fhir}Device"/>
 *         &lt;element ref="{http://hl7.org/fhir}DeviceComponent"/>
 *         &lt;element ref="{http://hl7.org/fhir}DeviceMetric"/>
 *         &lt;element ref="{http://hl7.org/fhir}DeviceUseRequest"/>
 *         &lt;element ref="{http://hl7.org/fhir}DeviceUseStatement"/>
 *         &lt;element ref="{http://hl7.org/fhir}DiagnosticOrder"/>
 *         &lt;element ref="{http://hl7.org/fhir}DiagnosticReport"/>
 *         &lt;element ref="{http://hl7.org/fhir}DocumentManifest"/>
 *         &lt;element ref="{http://hl7.org/fhir}DocumentReference"/>
 *         &lt;element ref="{http://hl7.org/fhir}EligibilityRequest"/>
 *         &lt;element ref="{http://hl7.org/fhir}EligibilityResponse"/>
 *         &lt;element ref="{http://hl7.org/fhir}Encounter"/>
 *         &lt;element ref="{http://hl7.org/fhir}EnrollmentRequest"/>
 *         &lt;element ref="{http://hl7.org/fhir}EnrollmentResponse"/>
 *         &lt;element ref="{http://hl7.org/fhir}EpisodeOfCare"/>
 *         &lt;element ref="{http://hl7.org/fhir}ExplanationOfBenefit"/>
 *         &lt;element ref="{http://hl7.org/fhir}FamilyMemberHistory"/>
 *         &lt;element ref="{http://hl7.org/fhir}Flag"/>
 *         &lt;element ref="{http://hl7.org/fhir}Goal"/>
 *         &lt;element ref="{http://hl7.org/fhir}Group"/>
 *         &lt;element ref="{http://hl7.org/fhir}HealthcareService"/>
 *         &lt;element ref="{http://hl7.org/fhir}ImagingObjectSelection"/>
 *         &lt;element ref="{http://hl7.org/fhir}ImagingStudy"/>
 *         &lt;element ref="{http://hl7.org/fhir}Immunization"/>
 *         &lt;element ref="{http://hl7.org/fhir}ImmunizationRecommendation"/>
 *         &lt;element ref="{http://hl7.org/fhir}ImplementationGuide"/>
 *         &lt;element ref="{http://hl7.org/fhir}List"/>
 *         &lt;element ref="{http://hl7.org/fhir}Location"/>
 *         &lt;element ref="{http://hl7.org/fhir}Media"/>
 *         &lt;element ref="{http://hl7.org/fhir}Medication"/>
 *         &lt;element ref="{http://hl7.org/fhir}MedicationAdministration"/>
 *         &lt;element ref="{http://hl7.org/fhir}MedicationDispense"/>
 *         &lt;element ref="{http://hl7.org/fhir}MedicationOrder"/>
 *         &lt;element ref="{http://hl7.org/fhir}MedicationStatement"/>
 *         &lt;element ref="{http://hl7.org/fhir}MessageHeader"/>
 *         &lt;element ref="{http://hl7.org/fhir}NamingSystem"/>
 *         &lt;element ref="{http://hl7.org/fhir}NutritionOrder"/>
 *         &lt;element ref="{http://hl7.org/fhir}Observation"/>
 *         &lt;element ref="{http://hl7.org/fhir}OperationDefinition"/>
 *         &lt;element ref="{http://hl7.org/fhir}OperationOutcome"/>
 *         &lt;element ref="{http://hl7.org/fhir}Order"/>
 *         &lt;element ref="{http://hl7.org/fhir}OrderResponse"/>
 *         &lt;element ref="{http://hl7.org/fhir}Organization"/>
 *         &lt;element ref="{http://hl7.org/fhir}Patient"/>
 *         &lt;element ref="{http://hl7.org/fhir}PaymentNotice"/>
 *         &lt;element ref="{http://hl7.org/fhir}PaymentReconciliation"/>
 *         &lt;element ref="{http://hl7.org/fhir}Person"/>
 *         &lt;element ref="{http://hl7.org/fhir}Practitioner"/>
 *         &lt;element ref="{http://hl7.org/fhir}Procedure"/>
 *         &lt;element ref="{http://hl7.org/fhir}ProcedureRequest"/>
 *         &lt;element ref="{http://hl7.org/fhir}ProcessRequest"/>
 *         &lt;element ref="{http://hl7.org/fhir}ProcessResponse"/>
 *         &lt;element ref="{http://hl7.org/fhir}Provenance"/>
 *         &lt;element ref="{http://hl7.org/fhir}Questionnaire"/>
 *         &lt;element ref="{http://hl7.org/fhir}QuestionnaireResponse"/>
 *         &lt;element ref="{http://hl7.org/fhir}ReferralRequest"/>
 *         &lt;element ref="{http://hl7.org/fhir}RelatedPerson"/>
 *         &lt;element ref="{http://hl7.org/fhir}RiskAssessment"/>
 *         &lt;element ref="{http://hl7.org/fhir}Schedule"/>
 *         &lt;element ref="{http://hl7.org/fhir}SearchParameter"/>
 *         &lt;element ref="{http://hl7.org/fhir}Slot"/>
 *         &lt;element ref="{http://hl7.org/fhir}Specimen"/>
 *         &lt;element ref="{http://hl7.org/fhir}StructureDefinition"/>
 *         &lt;element ref="{http://hl7.org/fhir}Subscription"/>
 *         &lt;element ref="{http://hl7.org/fhir}Substance"/>
 *         &lt;element ref="{http://hl7.org/fhir}SupplyDelivery"/>
 *         &lt;element ref="{http://hl7.org/fhir}SupplyRequest"/>
 *         &lt;element ref="{http://hl7.org/fhir}TestScript"/>
 *         &lt;element ref="{http://hl7.org/fhir}ValueSet"/>
 *         &lt;element ref="{http://hl7.org/fhir}VisionPrescription"/>
 *         &lt;element ref="{http://hl7.org/fhir}Parameters"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceContainer", propOrder = {
    "account",
    "allergyIntolerance",
    "appointment",
    "appointmentResponse",
    "auditEvent",
    "basic",
    "binary",
    "bodySite",
    "bundle",
    "carePlan",
    "claim",
    "claimResponse",
    "clinicalImpression",
    "communication",
    "communicationRequest",
    "composition",
    "conceptMap",
    "condition",
    "conformance",
    "contract",
    "coverage",
    "dataElement",
    "detectedIssue",
    "device",
    "deviceComponent",
    "deviceMetric",
    "deviceUseRequest",
    "deviceUseStatement",
    "diagnosticOrder",
    "diagnosticReport",
    "documentManifest",
    "documentReference",
    "eligibilityRequest",
    "eligibilityResponse",
    "encounter",
    "enrollmentRequest",
    "enrollmentResponse",
    "episodeOfCare",
    "explanationOfBenefit",
    "familyMemberHistory",
    "flag",
    "goal",
    "group",
    "healthcareService",
    "imagingObjectSelection",
    "imagingStudy",
    "immunization",
    "immunizationRecommendation",
    "implementationGuide",
    "list",
    "location",
    "media",
    "medication",
    "medicationAdministration",
    "medicationDispense",
    "medicationOrder",
    "medicationStatement",
    "messageHeader",
    "namingSystem",
    "nutritionOrder",
    "observation",
    "operationDefinition",
    "operationOutcome",
    "order",
    "orderResponse",
    "organization",
    "patient",
    "paymentNotice",
    "paymentReconciliation",
    "person",
    "practitioner",
    "procedure",
    "procedureRequest",
    "processRequest",
    "processResponse",
    "provenance",
    "questionnaire",
    "questionnaireResponse",
    "referralRequest",
    "relatedPerson",
    "riskAssessment",
    "schedule",
    "searchParameter",
    "slot",
    "specimen",
    "structureDefinition",
    "subscription",
    "substance",
    "supplyDelivery",
    "supplyRequest",
    "testScript",
    "valueSet",
    "visionPrescription",
    "parameters"
})
public class ResourceContainer {

    @XmlElement(name = "Account")
    protected Account account;
    @XmlElement(name = "AllergyIntolerance")
    protected AllergyIntolerance allergyIntolerance;
    @XmlElement(name = "Appointment")
    protected Appointment appointment;
    @XmlElement(name = "AppointmentResponse")
    protected AppointmentResponse appointmentResponse;
    @XmlElement(name = "AuditEvent")
    protected AuditEvent auditEvent;
    @XmlElement(name = "Basic")
    protected Basic basic;
    @XmlElement(name = "Binary")
    protected Binary binary;
    @XmlElement(name = "BodySite")
    protected BodySite bodySite;
    @XmlElement(name = "Bundle")
    protected Bundle bundle;
    @XmlElement(name = "CarePlan")
    protected CarePlan carePlan;
    @XmlElement(name = "Claim")
    protected Claim claim;
    @XmlElement(name = "ClaimResponse")
    protected ClaimResponse claimResponse;
    @XmlElement(name = "ClinicalImpression")
    protected ClinicalImpression clinicalImpression;
    @XmlElement(name = "Communication")
    protected Communication communication;
    @XmlElement(name = "CommunicationRequest")
    protected CommunicationRequest communicationRequest;
    @XmlElement(name = "Composition")
    protected Composition composition;
    @XmlElement(name = "ConceptMap")
    protected ConceptMap conceptMap;
    @XmlElement(name = "Condition")
    protected Condition condition;
    @XmlElement(name = "Conformance")
    protected Conformance conformance;
    @XmlElement(name = "Contract")
    protected Contract contract;
    @XmlElement(name = "Coverage")
    protected Coverage coverage;
    @XmlElement(name = "DataElement")
    protected DataElement dataElement;
    @XmlElement(name = "DetectedIssue")
    protected DetectedIssue detectedIssue;
    @XmlElement(name = "Device")
    protected Device device;
    @XmlElement(name = "DeviceComponent")
    protected DeviceComponent deviceComponent;
    @XmlElement(name = "DeviceMetric")
    protected DeviceMetric deviceMetric;
    @XmlElement(name = "DeviceUseRequest")
    protected DeviceUseRequest deviceUseRequest;
    @XmlElement(name = "DeviceUseStatement")
    protected DeviceUseStatement deviceUseStatement;
    @XmlElement(name = "DiagnosticOrder")
    protected DiagnosticOrder diagnosticOrder;
    @XmlElement(name = "DiagnosticReport")
    protected DiagnosticReport diagnosticReport;
    @XmlElement(name = "DocumentManifest")
    protected DocumentManifest documentManifest;
    @XmlElement(name = "DocumentReference")
    protected DocumentReference documentReference;
    @XmlElement(name = "EligibilityRequest")
    protected EligibilityRequest eligibilityRequest;
    @XmlElement(name = "EligibilityResponse")
    protected EligibilityResponse eligibilityResponse;
    @XmlElement(name = "Encounter")
    protected Encounter encounter;
    @XmlElement(name = "EnrollmentRequest")
    protected EnrollmentRequest enrollmentRequest;
    @XmlElement(name = "EnrollmentResponse")
    protected EnrollmentResponse enrollmentResponse;
    @XmlElement(name = "EpisodeOfCare")
    protected EpisodeOfCare episodeOfCare;
    @XmlElement(name = "ExplanationOfBenefit")
    protected ExplanationOfBenefit explanationOfBenefit;
    @XmlElement(name = "FamilyMemberHistory")
    protected FamilyMemberHistory familyMemberHistory;
    @XmlElement(name = "Flag")
    protected Flag flag;
    @XmlElement(name = "Goal")
    protected Goal goal;
    @XmlElement(name = "Group")
    protected Group group;
    @XmlElement(name = "HealthcareService")
    protected HealthcareService healthcareService;
    @XmlElement(name = "ImagingObjectSelection")
    protected ImagingObjectSelection imagingObjectSelection;
    @XmlElement(name = "ImagingStudy")
    protected ImagingStudy imagingStudy;
    @XmlElement(name = "Immunization")
    protected Immunization immunization;
    @XmlElement(name = "ImmunizationRecommendation")
    protected ImmunizationRecommendation immunizationRecommendation;
    @XmlElement(name = "ImplementationGuide")
    protected ImplementationGuide implementationGuide;
    @XmlElement(name = "List")
    protected List list;
    @XmlElement(name = "Location")
    protected Location location;
    @XmlElement(name = "Media")
    protected Media media;
    @XmlElement(name = "Medication")
    protected Medication medication;
    @XmlElement(name = "MedicationAdministration")
    protected MedicationAdministration medicationAdministration;
    @XmlElement(name = "MedicationDispense")
    protected MedicationDispense medicationDispense;
    @XmlElement(name = "MedicationOrder")
    protected MedicationOrder medicationOrder;
    @XmlElement(name = "MedicationStatement")
    protected MedicationStatement medicationStatement;
    @XmlElement(name = "MessageHeader")
    protected MessageHeader messageHeader;
    @XmlElement(name = "NamingSystem")
    protected NamingSystem namingSystem;
    @XmlElement(name = "NutritionOrder")
    protected NutritionOrder nutritionOrder;
    @XmlElement(name = "Observation")
    protected Observation observation;
    @XmlElement(name = "OperationDefinition")
    protected OperationDefinition operationDefinition;
    @XmlElement(name = "OperationOutcome")
    protected OperationOutcome operationOutcome;
    @XmlElement(name = "Order")
    protected Order order;
    @XmlElement(name = "OrderResponse")
    protected OrderResponse orderResponse;
    @XmlElement(name = "Organization")
    protected Organization organization;
    @XmlElement(name = "Patient")
    protected Patient patient;
    @XmlElement(name = "PaymentNotice")
    protected PaymentNotice paymentNotice;
    @XmlElement(name = "PaymentReconciliation")
    protected PaymentReconciliation paymentReconciliation;
    @XmlElement(name = "Person")
    protected Person person;
    @XmlElement(name = "Practitioner")
    protected Practitioner practitioner;
    @XmlElement(name = "Procedure")
    protected Procedure procedure;
    @XmlElement(name = "ProcedureRequest")
    protected ProcedureRequest procedureRequest;
    @XmlElement(name = "ProcessRequest")
    protected ProcessRequest processRequest;
    @XmlElement(name = "ProcessResponse")
    protected ProcessResponse processResponse;
    @XmlElement(name = "Provenance")
    protected Provenance provenance;
    @XmlElement(name = "Questionnaire")
    protected Questionnaire questionnaire;
    @XmlElement(name = "QuestionnaireResponse")
    protected QuestionnaireResponse questionnaireResponse;
    @XmlElement(name = "ReferralRequest")
    protected ReferralRequest referralRequest;
    @XmlElement(name = "RelatedPerson")
    protected RelatedPerson relatedPerson;
    @XmlElement(name = "RiskAssessment")
    protected RiskAssessment riskAssessment;
    @XmlElement(name = "Schedule")
    protected Schedule schedule;
    @XmlElement(name = "SearchParameter")
    protected SearchParameter searchParameter;
    @XmlElement(name = "Slot")
    protected Slot slot;
    @XmlElement(name = "Specimen")
    protected Specimen specimen;
    @XmlElement(name = "StructureDefinition")
    protected StructureDefinition structureDefinition;
    @XmlElement(name = "Subscription")
    protected Subscription subscription;
    @XmlElement(name = "Substance")
    protected Substance substance;
    @XmlElement(name = "SupplyDelivery")
    protected SupplyDelivery supplyDelivery;
    @XmlElement(name = "SupplyRequest")
    protected SupplyRequest supplyRequest;
    @XmlElement(name = "TestScript")
    protected TestScript testScript;
    @XmlElement(name = "ValueSet")
    protected ValueSet valueSet;
    @XmlElement(name = "VisionPrescription")
    protected VisionPrescription visionPrescription;
    @XmlElement(name = "Parameters")
    protected Parameters parameters;

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link Account }
     *     
     */
    public Account getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account }
     *     
     */
    public void setAccount(Account value) {
        this.account = value;
    }

    /**
     * Gets the value of the allergyIntolerance property.
     * 
     * @return
     *     possible object is
     *     {@link AllergyIntolerance }
     *     
     */
    public AllergyIntolerance getAllergyIntolerance() {
        return allergyIntolerance;
    }

    /**
     * Sets the value of the allergyIntolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllergyIntolerance }
     *     
     */
    public void setAllergyIntolerance(AllergyIntolerance value) {
        this.allergyIntolerance = value;
    }

    /**
     * Gets the value of the appointment property.
     * 
     * @return
     *     possible object is
     *     {@link Appointment }
     *     
     */
    public Appointment getAppointment() {
        return appointment;
    }

    /**
     * Sets the value of the appointment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Appointment }
     *     
     */
    public void setAppointment(Appointment value) {
        this.appointment = value;
    }

    /**
     * Gets the value of the appointmentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AppointmentResponse }
     *     
     */
    public AppointmentResponse getAppointmentResponse() {
        return appointmentResponse;
    }

    /**
     * Sets the value of the appointmentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppointmentResponse }
     *     
     */
    public void setAppointmentResponse(AppointmentResponse value) {
        this.appointmentResponse = value;
    }

    /**
     * Gets the value of the auditEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AuditEvent }
     *     
     */
    public AuditEvent getAuditEvent() {
        return auditEvent;
    }

    /**
     * Sets the value of the auditEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditEvent }
     *     
     */
    public void setAuditEvent(AuditEvent value) {
        this.auditEvent = value;
    }

    /**
     * Gets the value of the basic property.
     * 
     * @return
     *     possible object is
     *     {@link Basic }
     *     
     */
    public Basic getBasic() {
        return basic;
    }

    /**
     * Sets the value of the basic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Basic }
     *     
     */
    public void setBasic(Basic value) {
        this.basic = value;
    }

    /**
     * Gets the value of the binary property.
     * 
     * @return
     *     possible object is
     *     {@link Binary }
     *     
     */
    public Binary getBinary() {
        return binary;
    }

    /**
     * Sets the value of the binary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Binary }
     *     
     */
    public void setBinary(Binary value) {
        this.binary = value;
    }

    /**
     * Gets the value of the bodySite property.
     * 
     * @return
     *     possible object is
     *     {@link BodySite }
     *     
     */
    public BodySite getBodySite() {
        return bodySite;
    }

    /**
     * Sets the value of the bodySite property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodySite }
     *     
     */
    public void setBodySite(BodySite value) {
        this.bodySite = value;
    }

    /**
     * Gets the value of the bundle property.
     * 
     * @return
     *     possible object is
     *     {@link Bundle }
     *     
     */
    public Bundle getBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bundle }
     *     
     */
    public void setBundle(Bundle value) {
        this.bundle = value;
    }

    /**
     * Gets the value of the carePlan property.
     * 
     * @return
     *     possible object is
     *     {@link CarePlan }
     *     
     */
    public CarePlan getCarePlan() {
        return carePlan;
    }

    /**
     * Sets the value of the carePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarePlan }
     *     
     */
    public void setCarePlan(CarePlan value) {
        this.carePlan = value;
    }

    /**
     * Gets the value of the claim property.
     * 
     * @return
     *     possible object is
     *     {@link Claim }
     *     
     */
    public Claim getClaim() {
        return claim;
    }

    /**
     * Sets the value of the claim property.
     * 
     * @param value
     *     allowed object is
     *     {@link Claim }
     *     
     */
    public void setClaim(Claim value) {
        this.claim = value;
    }

    /**
     * Gets the value of the claimResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimResponse }
     *     
     */
    public ClaimResponse getClaimResponse() {
        return claimResponse;
    }

    /**
     * Sets the value of the claimResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimResponse }
     *     
     */
    public void setClaimResponse(ClaimResponse value) {
        this.claimResponse = value;
    }

    /**
     * Gets the value of the clinicalImpression property.
     * 
     * @return
     *     possible object is
     *     {@link ClinicalImpression }
     *     
     */
    public ClinicalImpression getClinicalImpression() {
        return clinicalImpression;
    }

    /**
     * Sets the value of the clinicalImpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClinicalImpression }
     *     
     */
    public void setClinicalImpression(ClinicalImpression value) {
        this.clinicalImpression = value;
    }

    /**
     * Gets the value of the communication property.
     * 
     * @return
     *     possible object is
     *     {@link Communication }
     *     
     */
    public Communication getCommunication() {
        return communication;
    }

    /**
     * Sets the value of the communication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Communication }
     *     
     */
    public void setCommunication(Communication value) {
        this.communication = value;
    }

    /**
     * Gets the value of the communicationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationRequest }
     *     
     */
    public CommunicationRequest getCommunicationRequest() {
        return communicationRequest;
    }

    /**
     * Sets the value of the communicationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationRequest }
     *     
     */
    public void setCommunicationRequest(CommunicationRequest value) {
        this.communicationRequest = value;
    }

    /**
     * Gets the value of the composition property.
     * 
     * @return
     *     possible object is
     *     {@link Composition }
     *     
     */
    public Composition getComposition() {
        return composition;
    }

    /**
     * Sets the value of the composition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition }
     *     
     */
    public void setComposition(Composition value) {
        this.composition = value;
    }

    /**
     * Gets the value of the conceptMap property.
     * 
     * @return
     *     possible object is
     *     {@link ConceptMap }
     *     
     */
    public ConceptMap getConceptMap() {
        return conceptMap;
    }

    /**
     * Sets the value of the conceptMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConceptMap }
     *     
     */
    public void setConceptMap(ConceptMap value) {
        this.conceptMap = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link Condition }
     *     
     */
    public Condition getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Condition }
     *     
     */
    public void setCondition(Condition value) {
        this.condition = value;
    }

    /**
     * Gets the value of the conformance property.
     * 
     * @return
     *     possible object is
     *     {@link Conformance }
     *     
     */
    public Conformance getConformance() {
        return conformance;
    }

    /**
     * Sets the value of the conformance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conformance }
     *     
     */
    public void setConformance(Conformance value) {
        this.conformance = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link Contract }
     *     
     */
    public Contract getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contract }
     *     
     */
    public void setContract(Contract value) {
        this.contract = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link Coverage }
     *     
     */
    public Coverage getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coverage }
     *     
     */
    public void setCoverage(Coverage value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the dataElement property.
     * 
     * @return
     *     possible object is
     *     {@link DataElement }
     *     
     */
    public DataElement getDataElement() {
        return dataElement;
    }

    /**
     * Sets the value of the dataElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataElement }
     *     
     */
    public void setDataElement(DataElement value) {
        this.dataElement = value;
    }

    /**
     * Gets the value of the detectedIssue property.
     * 
     * @return
     *     possible object is
     *     {@link DetectedIssue }
     *     
     */
    public DetectedIssue getDetectedIssue() {
        return detectedIssue;
    }

    /**
     * Sets the value of the detectedIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetectedIssue }
     *     
     */
    public void setDetectedIssue(DetectedIssue value) {
        this.detectedIssue = value;
    }

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link Device }
     *     
     */
    public Device getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link Device }
     *     
     */
    public void setDevice(Device value) {
        this.device = value;
    }

    /**
     * Gets the value of the deviceComponent property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceComponent }
     *     
     */
    public DeviceComponent getDeviceComponent() {
        return deviceComponent;
    }

    /**
     * Sets the value of the deviceComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceComponent }
     *     
     */
    public void setDeviceComponent(DeviceComponent value) {
        this.deviceComponent = value;
    }

    /**
     * Gets the value of the deviceMetric property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceMetric }
     *     
     */
    public DeviceMetric getDeviceMetric() {
        return deviceMetric;
    }

    /**
     * Sets the value of the deviceMetric property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceMetric }
     *     
     */
    public void setDeviceMetric(DeviceMetric value) {
        this.deviceMetric = value;
    }

    /**
     * Gets the value of the deviceUseRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceUseRequest }
     *     
     */
    public DeviceUseRequest getDeviceUseRequest() {
        return deviceUseRequest;
    }

    /**
     * Sets the value of the deviceUseRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceUseRequest }
     *     
     */
    public void setDeviceUseRequest(DeviceUseRequest value) {
        this.deviceUseRequest = value;
    }

    /**
     * Gets the value of the deviceUseStatement property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceUseStatement }
     *     
     */
    public DeviceUseStatement getDeviceUseStatement() {
        return deviceUseStatement;
    }

    /**
     * Sets the value of the deviceUseStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceUseStatement }
     *     
     */
    public void setDeviceUseStatement(DeviceUseStatement value) {
        this.deviceUseStatement = value;
    }

    /**
     * Gets the value of the diagnosticOrder property.
     * 
     * @return
     *     possible object is
     *     {@link DiagnosticOrder }
     *     
     */
    public DiagnosticOrder getDiagnosticOrder() {
        return diagnosticOrder;
    }

    /**
     * Sets the value of the diagnosticOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagnosticOrder }
     *     
     */
    public void setDiagnosticOrder(DiagnosticOrder value) {
        this.diagnosticOrder = value;
    }

    /**
     * Gets the value of the diagnosticReport property.
     * 
     * @return
     *     possible object is
     *     {@link DiagnosticReport }
     *     
     */
    public DiagnosticReport getDiagnosticReport() {
        return diagnosticReport;
    }

    /**
     * Sets the value of the diagnosticReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiagnosticReport }
     *     
     */
    public void setDiagnosticReport(DiagnosticReport value) {
        this.diagnosticReport = value;
    }

    /**
     * Gets the value of the documentManifest property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentManifest }
     *     
     */
    public DocumentManifest getDocumentManifest() {
        return documentManifest;
    }

    /**
     * Sets the value of the documentManifest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentManifest }
     *     
     */
    public void setDocumentManifest(DocumentManifest value) {
        this.documentManifest = value;
    }

    /**
     * Gets the value of the documentReference property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentReference }
     *     
     */
    public DocumentReference getDocumentReference() {
        return documentReference;
    }

    /**
     * Sets the value of the documentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentReference }
     *     
     */
    public void setDocumentReference(DocumentReference value) {
        this.documentReference = value;
    }

    /**
     * Gets the value of the eligibilityRequest property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityRequest }
     *     
     */
    public EligibilityRequest getEligibilityRequest() {
        return eligibilityRequest;
    }

    /**
     * Sets the value of the eligibilityRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityRequest }
     *     
     */
    public void setEligibilityRequest(EligibilityRequest value) {
        this.eligibilityRequest = value;
    }

    /**
     * Gets the value of the eligibilityResponse property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityResponse }
     *     
     */
    public EligibilityResponse getEligibilityResponse() {
        return eligibilityResponse;
    }

    /**
     * Sets the value of the eligibilityResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityResponse }
     *     
     */
    public void setEligibilityResponse(EligibilityResponse value) {
        this.eligibilityResponse = value;
    }

    /**
     * Gets the value of the encounter property.
     * 
     * @return
     *     possible object is
     *     {@link Encounter }
     *     
     */
    public Encounter getEncounter() {
        return encounter;
    }

    /**
     * Sets the value of the encounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Encounter }
     *     
     */
    public void setEncounter(Encounter value) {
        this.encounter = value;
    }

    /**
     * Gets the value of the enrollmentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollmentRequest }
     *     
     */
    public EnrollmentRequest getEnrollmentRequest() {
        return enrollmentRequest;
    }

    /**
     * Sets the value of the enrollmentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollmentRequest }
     *     
     */
    public void setEnrollmentRequest(EnrollmentRequest value) {
        this.enrollmentRequest = value;
    }

    /**
     * Gets the value of the enrollmentResponse property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollmentResponse }
     *     
     */
    public EnrollmentResponse getEnrollmentResponse() {
        return enrollmentResponse;
    }

    /**
     * Sets the value of the enrollmentResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollmentResponse }
     *     
     */
    public void setEnrollmentResponse(EnrollmentResponse value) {
        this.enrollmentResponse = value;
    }

    /**
     * Gets the value of the episodeOfCare property.
     * 
     * @return
     *     possible object is
     *     {@link EpisodeOfCare }
     *     
     */
    public EpisodeOfCare getEpisodeOfCare() {
        return episodeOfCare;
    }

    /**
     * Sets the value of the episodeOfCare property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpisodeOfCare }
     *     
     */
    public void setEpisodeOfCare(EpisodeOfCare value) {
        this.episodeOfCare = value;
    }

    /**
     * Gets the value of the explanationOfBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link ExplanationOfBenefit }
     *     
     */
    public ExplanationOfBenefit getExplanationOfBenefit() {
        return explanationOfBenefit;
    }

    /**
     * Sets the value of the explanationOfBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExplanationOfBenefit }
     *     
     */
    public void setExplanationOfBenefit(ExplanationOfBenefit value) {
        this.explanationOfBenefit = value;
    }

    /**
     * Gets the value of the familyMemberHistory property.
     * 
     * @return
     *     possible object is
     *     {@link FamilyMemberHistory }
     *     
     */
    public FamilyMemberHistory getFamilyMemberHistory() {
        return familyMemberHistory;
    }

    /**
     * Sets the value of the familyMemberHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FamilyMemberHistory }
     *     
     */
    public void setFamilyMemberHistory(FamilyMemberHistory value) {
        this.familyMemberHistory = value;
    }

    /**
     * Gets the value of the flag property.
     * 
     * @return
     *     possible object is
     *     {@link Flag }
     *     
     */
    public Flag getFlag() {
        return flag;
    }

    /**
     * Sets the value of the flag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flag }
     *     
     */
    public void setFlag(Flag value) {
        this.flag = value;
    }

    /**
     * Gets the value of the goal property.
     * 
     * @return
     *     possible object is
     *     {@link Goal }
     *     
     */
    public Goal getGoal() {
        return goal;
    }

    /**
     * Sets the value of the goal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Goal }
     *     
     */
    public void setGoal(Goal value) {
        this.goal = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Group }
     *     
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Group }
     *     
     */
    public void setGroup(Group value) {
        this.group = value;
    }

    /**
     * Gets the value of the healthcareService property.
     * 
     * @return
     *     possible object is
     *     {@link HealthcareService }
     *     
     */
    public HealthcareService getHealthcareService() {
        return healthcareService;
    }

    /**
     * Sets the value of the healthcareService property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthcareService }
     *     
     */
    public void setHealthcareService(HealthcareService value) {
        this.healthcareService = value;
    }

    /**
     * Gets the value of the imagingObjectSelection property.
     * 
     * @return
     *     possible object is
     *     {@link ImagingObjectSelection }
     *     
     */
    public ImagingObjectSelection getImagingObjectSelection() {
        return imagingObjectSelection;
    }

    /**
     * Sets the value of the imagingObjectSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagingObjectSelection }
     *     
     */
    public void setImagingObjectSelection(ImagingObjectSelection value) {
        this.imagingObjectSelection = value;
    }

    /**
     * Gets the value of the imagingStudy property.
     * 
     * @return
     *     possible object is
     *     {@link ImagingStudy }
     *     
     */
    public ImagingStudy getImagingStudy() {
        return imagingStudy;
    }

    /**
     * Sets the value of the imagingStudy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagingStudy }
     *     
     */
    public void setImagingStudy(ImagingStudy value) {
        this.imagingStudy = value;
    }

    /**
     * Gets the value of the immunization property.
     * 
     * @return
     *     possible object is
     *     {@link Immunization }
     *     
     */
    public Immunization getImmunization() {
        return immunization;
    }

    /**
     * Sets the value of the immunization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Immunization }
     *     
     */
    public void setImmunization(Immunization value) {
        this.immunization = value;
    }

    /**
     * Gets the value of the immunizationRecommendation property.
     * 
     * @return
     *     possible object is
     *     {@link ImmunizationRecommendation }
     *     
     */
    public ImmunizationRecommendation getImmunizationRecommendation() {
        return immunizationRecommendation;
    }

    /**
     * Sets the value of the immunizationRecommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImmunizationRecommendation }
     *     
     */
    public void setImmunizationRecommendation(ImmunizationRecommendation value) {
        this.immunizationRecommendation = value;
    }

    /**
     * Gets the value of the implementationGuide property.
     * 
     * @return
     *     possible object is
     *     {@link ImplementationGuide }
     *     
     */
    public ImplementationGuide getImplementationGuide() {
        return implementationGuide;
    }

    /**
     * Sets the value of the implementationGuide property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImplementationGuide }
     *     
     */
    public void setImplementationGuide(ImplementationGuide value) {
        this.implementationGuide = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link List }
     *     
     */
    public List getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link List }
     *     
     */
    public void setList(List value) {
        this.list = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link Media }
     *     
     */
    public Media getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link Media }
     *     
     */
    public void setMedia(Media value) {
        this.media = value;
    }

    /**
     * Gets the value of the medication property.
     * 
     * @return
     *     possible object is
     *     {@link Medication }
     *     
     */
    public Medication getMedication() {
        return medication;
    }

    /**
     * Sets the value of the medication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medication }
     *     
     */
    public void setMedication(Medication value) {
        this.medication = value;
    }

    /**
     * Gets the value of the medicationAdministration property.
     * 
     * @return
     *     possible object is
     *     {@link MedicationAdministration }
     *     
     */
    public MedicationAdministration getMedicationAdministration() {
        return medicationAdministration;
    }

    /**
     * Sets the value of the medicationAdministration property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicationAdministration }
     *     
     */
    public void setMedicationAdministration(MedicationAdministration value) {
        this.medicationAdministration = value;
    }

    /**
     * Gets the value of the medicationDispense property.
     * 
     * @return
     *     possible object is
     *     {@link MedicationDispense }
     *     
     */
    public MedicationDispense getMedicationDispense() {
        return medicationDispense;
    }

    /**
     * Sets the value of the medicationDispense property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicationDispense }
     *     
     */
    public void setMedicationDispense(MedicationDispense value) {
        this.medicationDispense = value;
    }

    /**
     * Gets the value of the medicationOrder property.
     * 
     * @return
     *     possible object is
     *     {@link MedicationOrder }
     *     
     */
    public MedicationOrder getMedicationOrder() {
        return medicationOrder;
    }

    /**
     * Sets the value of the medicationOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicationOrder }
     *     
     */
    public void setMedicationOrder(MedicationOrder value) {
        this.medicationOrder = value;
    }

    /**
     * Gets the value of the medicationStatement property.
     * 
     * @return
     *     possible object is
     *     {@link MedicationStatement }
     *     
     */
    public MedicationStatement getMedicationStatement() {
        return medicationStatement;
    }

    /**
     * Sets the value of the medicationStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicationStatement }
     *     
     */
    public void setMedicationStatement(MedicationStatement value) {
        this.medicationStatement = value;
    }

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the namingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link NamingSystem }
     *     
     */
    public NamingSystem getNamingSystem() {
        return namingSystem;
    }

    /**
     * Sets the value of the namingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamingSystem }
     *     
     */
    public void setNamingSystem(NamingSystem value) {
        this.namingSystem = value;
    }

    /**
     * Gets the value of the nutritionOrder property.
     * 
     * @return
     *     possible object is
     *     {@link NutritionOrder }
     *     
     */
    public NutritionOrder getNutritionOrder() {
        return nutritionOrder;
    }

    /**
     * Sets the value of the nutritionOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link NutritionOrder }
     *     
     */
    public void setNutritionOrder(NutritionOrder value) {
        this.nutritionOrder = value;
    }

    /**
     * Gets the value of the observation property.
     * 
     * @return
     *     possible object is
     *     {@link Observation }
     *     
     */
    public Observation getObservation() {
        return observation;
    }

    /**
     * Sets the value of the observation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Observation }
     *     
     */
    public void setObservation(Observation value) {
        this.observation = value;
    }

    /**
     * Gets the value of the operationDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link OperationDefinition }
     *     
     */
    public OperationDefinition getOperationDefinition() {
        return operationDefinition;
    }

    /**
     * Sets the value of the operationDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationDefinition }
     *     
     */
    public void setOperationDefinition(OperationDefinition value) {
        this.operationDefinition = value;
    }

    /**
     * Gets the value of the operationOutcome property.
     * 
     * @return
     *     possible object is
     *     {@link OperationOutcome }
     *     
     */
    public OperationOutcome getOperationOutcome() {
        return operationOutcome;
    }

    /**
     * Sets the value of the operationOutcome property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationOutcome }
     *     
     */
    public void setOperationOutcome(OperationOutcome value) {
        this.operationOutcome = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the orderResponse property.
     * 
     * @return
     *     possible object is
     *     {@link OrderResponse }
     *     
     */
    public OrderResponse getOrderResponse() {
        return orderResponse;
    }

    /**
     * Sets the value of the orderResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderResponse }
     *     
     */
    public void setOrderResponse(OrderResponse value) {
        this.orderResponse = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setOrganization(Organization value) {
        this.organization = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link Patient }
     *     
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patient }
     *     
     */
    public void setPatient(Patient value) {
        this.patient = value;
    }

    /**
     * Gets the value of the paymentNotice property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentNotice }
     *     
     */
    public PaymentNotice getPaymentNotice() {
        return paymentNotice;
    }

    /**
     * Sets the value of the paymentNotice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentNotice }
     *     
     */
    public void setPaymentNotice(PaymentNotice value) {
        this.paymentNotice = value;
    }

    /**
     * Gets the value of the paymentReconciliation property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentReconciliation }
     *     
     */
    public PaymentReconciliation getPaymentReconciliation() {
        return paymentReconciliation;
    }

    /**
     * Sets the value of the paymentReconciliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentReconciliation }
     *     
     */
    public void setPaymentReconciliation(PaymentReconciliation value) {
        this.paymentReconciliation = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the practitioner property.
     * 
     * @return
     *     possible object is
     *     {@link Practitioner }
     *     
     */
    public Practitioner getPractitioner() {
        return practitioner;
    }

    /**
     * Sets the value of the practitioner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Practitioner }
     *     
     */
    public void setPractitioner(Practitioner value) {
        this.practitioner = value;
    }

    /**
     * Gets the value of the procedure property.
     * 
     * @return
     *     possible object is
     *     {@link Procedure }
     *     
     */
    public Procedure getProcedure() {
        return procedure;
    }

    /**
     * Sets the value of the procedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Procedure }
     *     
     */
    public void setProcedure(Procedure value) {
        this.procedure = value;
    }

    /**
     * Gets the value of the procedureRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ProcedureRequest }
     *     
     */
    public ProcedureRequest getProcedureRequest() {
        return procedureRequest;
    }

    /**
     * Sets the value of the procedureRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcedureRequest }
     *     
     */
    public void setProcedureRequest(ProcedureRequest value) {
        this.procedureRequest = value;
    }

    /**
     * Gets the value of the processRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessRequest }
     *     
     */
    public ProcessRequest getProcessRequest() {
        return processRequest;
    }

    /**
     * Sets the value of the processRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessRequest }
     *     
     */
    public void setProcessRequest(ProcessRequest value) {
        this.processRequest = value;
    }

    /**
     * Gets the value of the processResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessResponse }
     *     
     */
    public ProcessResponse getProcessResponse() {
        return processResponse;
    }

    /**
     * Sets the value of the processResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessResponse }
     *     
     */
    public void setProcessResponse(ProcessResponse value) {
        this.processResponse = value;
    }

    /**
     * Gets the value of the provenance property.
     * 
     * @return
     *     possible object is
     *     {@link Provenance }
     *     
     */
    public Provenance getProvenance() {
        return provenance;
    }

    /**
     * Sets the value of the provenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Provenance }
     *     
     */
    public void setProvenance(Provenance value) {
        this.provenance = value;
    }

    /**
     * Gets the value of the questionnaire property.
     * 
     * @return
     *     possible object is
     *     {@link Questionnaire }
     *     
     */
    public Questionnaire getQuestionnaire() {
        return questionnaire;
    }

    /**
     * Sets the value of the questionnaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link Questionnaire }
     *     
     */
    public void setQuestionnaire(Questionnaire value) {
        this.questionnaire = value;
    }

    /**
     * Gets the value of the questionnaireResponse property.
     * 
     * @return
     *     possible object is
     *     {@link QuestionnaireResponse }
     *     
     */
    public QuestionnaireResponse getQuestionnaireResponse() {
        return questionnaireResponse;
    }

    /**
     * Sets the value of the questionnaireResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuestionnaireResponse }
     *     
     */
    public void setQuestionnaireResponse(QuestionnaireResponse value) {
        this.questionnaireResponse = value;
    }

    /**
     * Gets the value of the referralRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ReferralRequest }
     *     
     */
    public ReferralRequest getReferralRequest() {
        return referralRequest;
    }

    /**
     * Sets the value of the referralRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferralRequest }
     *     
     */
    public void setReferralRequest(ReferralRequest value) {
        this.referralRequest = value;
    }

    /**
     * Gets the value of the relatedPerson property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedPerson }
     *     
     */
    public RelatedPerson getRelatedPerson() {
        return relatedPerson;
    }

    /**
     * Sets the value of the relatedPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedPerson }
     *     
     */
    public void setRelatedPerson(RelatedPerson value) {
        this.relatedPerson = value;
    }

    /**
     * Gets the value of the riskAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link RiskAssessment }
     *     
     */
    public RiskAssessment getRiskAssessment() {
        return riskAssessment;
    }

    /**
     * Sets the value of the riskAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskAssessment }
     *     
     */
    public void setRiskAssessment(RiskAssessment value) {
        this.riskAssessment = value;
    }

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule }
     *     
     */
    public Schedule getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule }
     *     
     */
    public void setSchedule(Schedule value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the searchParameter property.
     * 
     * @return
     *     possible object is
     *     {@link SearchParameter }
     *     
     */
    public SearchParameter getSearchParameter() {
        return searchParameter;
    }

    /**
     * Sets the value of the searchParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchParameter }
     *     
     */
    public void setSearchParameter(SearchParameter value) {
        this.searchParameter = value;
    }

    /**
     * Gets the value of the slot property.
     * 
     * @return
     *     possible object is
     *     {@link Slot }
     *     
     */
    public Slot getSlot() {
        return slot;
    }

    /**
     * Sets the value of the slot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Slot }
     *     
     */
    public void setSlot(Slot value) {
        this.slot = value;
    }

    /**
     * Gets the value of the specimen property.
     * 
     * @return
     *     possible object is
     *     {@link Specimen }
     *     
     */
    public Specimen getSpecimen() {
        return specimen;
    }

    /**
     * Sets the value of the specimen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Specimen }
     *     
     */
    public void setSpecimen(Specimen value) {
        this.specimen = value;
    }

    /**
     * Gets the value of the structureDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link StructureDefinition }
     *     
     */
    public StructureDefinition getStructureDefinition() {
        return structureDefinition;
    }

    /**
     * Sets the value of the structureDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructureDefinition }
     *     
     */
    public void setStructureDefinition(StructureDefinition value) {
        this.structureDefinition = value;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * @return
     *     possible object is
     *     {@link Subscription }
     *     
     */
    public Subscription getSubscription() {
        return subscription;
    }

    /**
     * Sets the value of the subscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subscription }
     *     
     */
    public void setSubscription(Subscription value) {
        this.subscription = value;
    }

    /**
     * Gets the value of the substance property.
     * 
     * @return
     *     possible object is
     *     {@link Substance }
     *     
     */
    public Substance getSubstance() {
        return substance;
    }

    /**
     * Sets the value of the substance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Substance }
     *     
     */
    public void setSubstance(Substance value) {
        this.substance = value;
    }

    /**
     * Gets the value of the supplyDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link SupplyDelivery }
     *     
     */
    public SupplyDelivery getSupplyDelivery() {
        return supplyDelivery;
    }

    /**
     * Sets the value of the supplyDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplyDelivery }
     *     
     */
    public void setSupplyDelivery(SupplyDelivery value) {
        this.supplyDelivery = value;
    }

    /**
     * Gets the value of the supplyRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SupplyRequest }
     *     
     */
    public SupplyRequest getSupplyRequest() {
        return supplyRequest;
    }

    /**
     * Sets the value of the supplyRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplyRequest }
     *     
     */
    public void setSupplyRequest(SupplyRequest value) {
        this.supplyRequest = value;
    }

    /**
     * Gets the value of the testScript property.
     * 
     * @return
     *     possible object is
     *     {@link TestScript }
     *     
     */
    public TestScript getTestScript() {
        return testScript;
    }

    /**
     * Sets the value of the testScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestScript }
     *     
     */
    public void setTestScript(TestScript value) {
        this.testScript = value;
    }

    /**
     * Gets the value of the valueSet property.
     * 
     * @return
     *     possible object is
     *     {@link ValueSet }
     *     
     */
    public ValueSet getValueSet() {
        return valueSet;
    }

    /**
     * Sets the value of the valueSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueSet }
     *     
     */
    public void setValueSet(ValueSet value) {
        this.valueSet = value;
    }

    /**
     * Gets the value of the visionPrescription property.
     * 
     * @return
     *     possible object is
     *     {@link VisionPrescription }
     *     
     */
    public VisionPrescription getVisionPrescription() {
        return visionPrescription;
    }

    /**
     * Sets the value of the visionPrescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisionPrescription }
     *     
     */
    public void setVisionPrescription(VisionPrescription value) {
        this.visionPrescription = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

}
